# Generated by Django 5.2.7 on 2025-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_icon_service_start_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_hero_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
