# Generated by Django 5.2.7 on 2025-10-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_servicecontent_options_servicerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerating',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service.service'),
        ),
    ]
