# Generated by Django 6.0a1 on 2025-11-10 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_servicerating_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
