# Generated by Django 6.0a1 on 2025-11-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_service_hero_image_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='addon',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='addoncategory',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='addoncategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='package',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duration (Arabic)'),
        ),
        migrations.AddField(
            model_name='package',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='package',
            name='square_feet_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Square Feet (Arabic)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_description_ar',
            field=models.TextField(blank=True, verbose_name='Hero Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='service',
            name='sub_hero_title_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Hero Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='servicecontent',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='description_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)'),
        ),
    ]
