# Generated by Django 5.2.7 on 2025-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Bright Scope UAE', max_length=200)),
                ('tagline', models.TextField(default='Your trusted cleaning and pest control partner in Dubai. 15+ years of excellence from Egypt to the UAE, serving thousands of satisfied customers.')),
                ('phone_number', models.CharField(default='+971 XXX XXX XXX', max_length=20)),
                ('whatsapp_number', models.CharField(default='+971 XXX XXX XXX', max_length=20)),
                ('address', models.TextField(default='Business Bay, Dubai, UAE')),
                ('building', models.CharField(default='Building XYZ', max_length=100)),
                ('office', models.CharField(default='Office 123', max_length=50)),
                ('mon_fri_hours', models.CharField(default='8:00 AM - 8:00 PM', max_length=100)),
                ('saturday_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('sunday_hours', models.CharField(default='10:00 AM - 5:00 PM', max_length=100)),
                ('emergency_available', models.BooleanField(default=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(default='© 2024 Bright Scope Dubai. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
