# Generated by Django 5.2.7 on 2025-10-24 13:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='QuickLink',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='id',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='subscribed_at',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(default='Business Bay, Dubai, UAE'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='building',
            field=models.CharField(default='Building XYZ', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='company_name',
            field=models.CharField(default='Bright Scope UAE', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='copyright_text',
            field=models.CharField(default='© 2024 Bright Scope Dubai. All rights reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='mon_fri_hours',
            field=models.CharField(default='8:00 AM - 8:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office',
            field=models.CharField(default='Office 123', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(default='+971 XXX XXX XXX', max_length=20),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='saturday_hours',
            field=models.CharField(default='9:00 AM - 6:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='sunday_hours',
            field=models.CharField(default='10:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='tagline',
            field=models.TextField(default='Your trusted cleaning and pest control partner in Dubai. 15+ years of excellence from Egypt to the UAE, serving thousands of satisfied customers.'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp_number',
            field=models.CharField(default='+971 XXX XXX XXX', max_length=20),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=datetime.datetime(2025, 10, 24, 13, 43, 30, 460360, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='settings.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=datetime.datetime(2025, 10, 24, 13, 43, 37, 536275, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='settings.basemodel'),
            preserve_default=False,
        ),
    ]
