# Generated by Django 6.0a1 on 2025-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address_ar',
            field=models.TextField(default='الخليج التجاري، دبي، الإمارات'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='building_ar',
            field=models.CharField(default='مبنى XYZ', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='company_name_ar',
            field=models.CharField(default='برايت سكوب الإمارات', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='copyright_text_ar',
            field=models.CharField(default='© ٢٠٢٤ برايت سكوب دبي. جميع الحقوق محفوظة.', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='mon_fri_hours_ar',
            field=models.CharField(default='٨:٠٠ ص - ٨:٠٠ م', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='office_ar',
            field=models.CharField(default='المكتب 123', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='saturday_hours_ar',
            field=models.CharField(default='٩:٠٠ ص - ٦:٠٠ م', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='sunday_hours_ar',
            field=models.CharField(default='١٠:٠٠ ص - ٥:٠٠ م', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='tagline_ar',
            field=models.TextField(default='شريكك الموثوق في التنظيف ومكافحة الحشرات في دبي. أكثر من 15 عامًا من التميز من مصر إلى الإمارات، نخدم آلاف العملاء الراضين.'),
        ),
    ]
