# Generated by Django 5.2.7 on 2025-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-map-pin', max_length=100, null=True)),
                ('method_type', models.CharField(choices=[('phone', 'Call Us'), ('whatsapp', 'WhatsApp Us'), ('email', 'Email Support')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value', models.CharField(help_text='Phone number, email, or address', max_length=200)),
                ('action_text', models.CharField(blank=True, help_text="e.g., 'Chat Now'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'method_type'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('residential', 'Residential Cleaning'), ('commercial', 'Commercial Cleaning'), ('deep_clean', 'Deep Cleaning'), ('move_in_out', 'Move In/Out Cleaning'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, default='fa-solid fa-map-pin', max_length=100, null=True)),
                ('title', models.CharField(default='Visit Our Office', max_length=255)),
                ('description', models.CharField(default='Come visit us at our Dubai headquarters for in-person consultations.', max_length=255)),
                ('office_name', models.CharField(default='Business Bay, Dubai', max_length=100)),
                ('office_address', models.CharField(default='United Arab Emirates', max_length=100)),
                ('working_hours_name', models.CharField(default='Working Hours', max_length=100)),
                ('working_hours_weekdays', models.CharField(default='Mon-Fri: 8AM-8PM | Sat: 9AM-6PM', max_length=200)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
