# Generated by Django 6.0a1 on 2025-11-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='service_type',
            field=models.CharField(choices=[('consulting', 'Consulting'), ('support', 'Support'), ('others', 'Other')], max_length=20),
        ),
    ]
