# Generated by Django 6.0a1 on 2025-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactsubmission_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmethod',
            options={'ordering': ['order', 'method_type'], 'verbose_name': 'Contact Method', 'verbose_name_plural': 'Contact Methods'},
        ),
        migrations.AlterModelOptions(
            name='officelocation',
            options={'verbose_name': 'Office Location', 'verbose_name_plural': 'Office Locations'},
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='action_text_ar',
            field=models.CharField(blank=True, max_length=50, verbose_name='Action Text (Arabic)'),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='title_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='description_ar',
            field=models.CharField(blank=True, default='تعال لزيارتنا في مقرنا الرئيسي في دبي للحصول على استشارات شخصية.', max_length=255, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='office_address_ar',
            field=models.CharField(blank=True, default='الإمارات العربية المتحدة', max_length=100, verbose_name='Office Address (Arabic)'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='office_name_ar',
            field=models.CharField(blank=True, default='الخليج التجاري, دبي', max_length=100, verbose_name='Office Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='title_ar',
            field=models.CharField(blank=True, default='زيارة مكتبنا', max_length=255, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='working_hours_name_ar',
            field=models.CharField(blank=True, default='ساعات العمل', max_length=100, verbose_name='Working Hours Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='working_hours_weekdays_ar',
            field=models.CharField(blank=True, default='الإثنين-الجمعة: 8 صباحاً-8 مساءً | السبت: 9 صباحاً-6 مساءً', max_length=200, verbose_name='Working Hours Weekdays (Arabic)'),
        ),
    ]
