# Generated by Django 6.0a1 on 2025-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_alter_contactmethod_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='action_text_ar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-phone', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='title_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='description_ar',
            field=models.CharField(blank=True, default='تعال لزيارتنا في مقرنا الرئيسي في دبي للحصول على استشارات شخصية.', max_length=255),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='office_address_ar',
            field=models.CharField(blank=True, default='الإمارات العربية المتحدة', max_length=100),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='office_name_ar',
            field=models.CharField(blank=True, default='الخليج التجاري, دبي', max_length=100),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='title_ar',
            field=models.CharField(blank=True, default='زيارة مكتبنا', max_length=255),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='working_hours_name_ar',
            field=models.CharField(blank=True, default='ساعات العمل', max_length=100),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='working_hours_weekdays_ar',
            field=models.CharField(blank=True, default='الإثنين-الجمعة: 8 صباحاً-8 مساءً | السبت: 9 صباحاً-6 مساءً', max_length=200),
        ),
    ]
